version: '3'

services:
  springboot-docker-compose-app-container:
    image: spring-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/spring-docker-compose
    ports:
      - "8082:8082"