version: '3'

services:
  springboot-docker-compose-app-container:
    image: spring-docker-compose:1
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: spring-docker-compose
    restart: always
    logging:
      driver: json-file
    volumes:
      - /data/spring-docker-compose
    ports:
      - "10.201.118.4:8082:8082"





